version: "3.5"

services:
  influxdb:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - HEALTH_CHECK_URL=${HEALTH_CHECK_URL}
